# Generated by Django 3.1.7 on 2021-03-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210312_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='title',
            field=models.CharField(default='2021/03/13 10:56', max_length=128),
        ),
    ]
